/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.JTableHeader;
import controlador.Usuarios;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


/**
 *
 * @author Cathecita
 */
public class FrmAdminUsuarios extends javax.swing.JFrame {
    
    

    
    public FrmAdminUsuarios() {
        initComponents();
        llenarJtable();
               
        //Color verdeOscuro = new Color(52,78,65);
        jTable_ADMIN_USUARIOS.setShowGrid(true);
        
        //Personalizar FRONT tabla colores según identidad corporativa webpet
        jTable_ADMIN_USUARIOS.setGridColor(Color.decode("#A3B18A"));
        jTable_ADMIN_USUARIOS.setSelectionBackground(Color.decode("#344E41"));
        jTable_ADMIN_USUARIOS.setSelectionForeground(Color.decode("#DAD7CD"));
        JTableHeader th = jTable_ADMIN_USUARIOS.getTableHeader();
        th.setFont(new Font("Montserrat", Font.BOLD, 12));
        
        
    }
    
    public void llenarJtable(){
        //traer usuarios del controlador
        controlador.Usuarios usuario = new controlador.Usuarios();
        ArrayList<controlador.Usuarios> listausuarios = usuario.ListaUsuarios();
        
            
        //Encabezado de la tabla independiente a variables y a mysql
        String[] colNames = {"Nombre","Apellido","Documento","Email","Usuario","Rol"};
             
        Object[][] rows = new Object[listausuarios.size()][6];
       
        for(int i = 0; i < listausuarios.size(); i++){
            rows[i][0] = listausuarios.get(i).getPri_nom_usuario();
            rows[i][1] = listausuarios.get(i).getPri_apell_usuario();
            rows[i][2] = listausuarios.get(i).getNum_doc_usuario();
            rows[i][3] = listausuarios.get(i).getEmail_usuario();
            rows[i][4] = listausuarios.get(i).getUsuario();
            rows[i][5] = listausuarios.get(i).getRol_usuario();
           
        }
       
        modelo.MyTableModelUsuarios mmd = new modelo.MyTableModelUsuarios(rows, colNames);
        jTable_ADMIN_USUARIOS.setModel(mmd);
        jTable_ADMIN_USUARIOS.setRowHeight(80);
        
        // DESDE INDEX 
        jTable_ADMIN_USUARIOS.getColumnModel().getColumn(5).setPreferredWidth(120);
        
        
    }
    
    //prueba con parámetros
    /*
    public void llenarJtableParam(String val){
        
        controlador.Usuarios usu = new controlador.Usuarios();
        ArrayList<controlador.Usuarios> listausuarios = usu.ListarUsuariosParam(val);
        
        String[] colNames = {"Nombre","Apellido","Documento","Email","Usuario","Rol"};
        Object[][] rows = new Object[listausuarios.size()][6];
        
        for(int i = 0; i < listausuarios.size(); i++){
            rows[i][0] = listausuarios.get(i).getPri_nom_usuario();
            rows[i][1] = listausuarios.get(i).getPri_apell_usuario();
            rows[i][2] = listausuarios.get(i).getNum_doc_usuario();
            rows[i][3] = listausuarios.get(i).getEmail_usuario();
            rows[i][4] = listausuarios.get(i).getUsuario();
            rows[i][5] = listausuarios.get(i).getRol_usuario();
           
        }
        
        modelo.MyTableModelUsuarios mmd = new modelo.MyTableModelUsuarios(rows, colNames);
        jTable_USUARIOS.setModel(mmd);
        jTable_USUARIOS.setRowHeight(80);
        jTable_USUARIOS.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTable_USUARIOS.getColumnModel().getColumn(3).setPreferredWidth(120);
    }
    */
    /*
    */
    
    
    
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_BUSCAR_USU = new javax.swing.JButton();
        jButton_ACTUALIZAR_USU = new javax.swing.JButton();
        jTextField_VALOR_BUSQUEDA_USU = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ADMIN_USUARIOS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 78, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/webpetdef 50px.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(218, 215, 205));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Hecho con ♥ por Catherine Escobar SENA ADSO CBA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(39, 39, 39))
        );

        jButton_BUSCAR_USU.setBackground(new java.awt.Color(218, 215, 205));
        jButton_BUSCAR_USU.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_BUSCAR_USU.setForeground(new java.awt.Color(52, 78, 65));
        jButton_BUSCAR_USU.setText("Buscar");
        jButton_BUSCAR_USU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BUSCAR_USUActionPerformed(evt);
            }
        });

        jButton_ACTUALIZAR_USU.setBackground(new java.awt.Color(52, 78, 65));
        jButton_ACTUALIZAR_USU.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ACTUALIZAR_USU.setForeground(new java.awt.Color(218, 215, 205));
        jButton_ACTUALIZAR_USU.setText("Actualizar");

        jTextField_VALOR_BUSQUEDA_USU.setBackground(new java.awt.Color(218, 215, 205));
        jTextField_VALOR_BUSQUEDA_USU.setForeground(new java.awt.Color(52, 78, 65));

        jScrollPane1.setViewportView(jTable_ADMIN_USUARIOS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_VALOR_BUSQUEDA_USU)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_BUSCAR_USU)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ACTUALIZAR_USU))
                    .addComponent(jScrollPane1))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_BUSCAR_USU)
                        .addComponent(jButton_ACTUALIZAR_USU)
                        .addComponent(jTextField_VALOR_BUSQUEDA_USU, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BUSCAR_USUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BUSCAR_USUActionPerformed
        // TODO add your handling code here:
         //populateJtable(jTextField_VALOR_BUSQUEDA_USU.getText());
    }//GEN-LAST:event_jButton_BUSCAR_USUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ACTUALIZAR_USU;
    private javax.swing.JButton jButton_BUSCAR_USU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_ADMIN_USUARIOS;
    private javax.swing.JTextField jTextField_VALOR_BUSQUEDA_USU;
    // End of variables declaration//GEN-END:variables
}
