/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Cathecita
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_INICIO = new javax.swing.JMenu();
        jMenu_USUARIOS = new javax.swing.JMenu();
        jMenuItem_REGISTRAR_USUARIO = new javax.swing.JMenuItem();
        jMenu_CLIENTES = new javax.swing.JMenu();
        jMenuItem_REGISTRAR_CLIENTE = new javax.swing.JMenuItem();
        jMenu_PROVEEDORES = new javax.swing.JMenu();
        jMenu_MASCOTAS = new javax.swing.JMenu();
        jMenu_AGENDA = new javax.swing.JMenu();
        jMenu_PRODUCTOS = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(218, 215, 205));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/webpetdef 50px.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(163, 177, 138));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Hecho con ♥ por Catherine Escobar SENA ADSO CBA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(50, 50, 50))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 78, 65));
        jLabel3.setText("Bienvenid@ a WebPet, el mejor software de gestión veterinaria.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(187, 187, 187)
                .addComponent(jLabel3)
                .addGap(174, 174, 174)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(739, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu_INICIO.setText("INICIO  |");
        jMenu_INICIO.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu_INICIO);

        jMenu_USUARIOS.setBackground(new java.awt.Color(255, 255, 255));
        jMenu_USUARIOS.setText("USUARIOS  |");
        jMenu_USUARIOS.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenu_USUARIOS.setMinimumSize(new java.awt.Dimension(105, 30));
        jMenu_USUARIOS.setPreferredSize(new java.awt.Dimension(105, 30));

        jMenuItem_REGISTRAR_USUARIO.setText("Registrar");
        jMenuItem_REGISTRAR_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_REGISTRAR_USUARIOActionPerformed(evt);
            }
        });
        jMenu_USUARIOS.add(jMenuItem_REGISTRAR_USUARIO);

        jMenuBar1.add(jMenu_USUARIOS);

        jMenu_CLIENTES.setText("CLIENTES |");
        jMenu_CLIENTES.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N

        jMenuItem_REGISTRAR_CLIENTE.setText("Registrar");
        jMenuItem_REGISTRAR_CLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_REGISTRAR_CLIENTEActionPerformed(evt);
            }
        });
        jMenu_CLIENTES.add(jMenuItem_REGISTRAR_CLIENTE);

        jMenuBar1.add(jMenu_CLIENTES);

        jMenu_PROVEEDORES.setText("PROVEEDORES |");
        jMenu_PROVEEDORES.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu_PROVEEDORES);

        jMenu_MASCOTAS.setText("MASCOTAS |");
        jMenu_MASCOTAS.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu_MASCOTAS);

        jMenu_AGENDA.setText("AGENDA |");
        jMenu_AGENDA.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu_AGENDA);

        jMenu_PRODUCTOS.setText("PRODUCTOS");
        jMenu_PRODUCTOS.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu_PRODUCTOS);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_REGISTRAR_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_REGISTRAR_USUARIOActionPerformed
        // TODO add your handling code here:
        vista.FrmRegistro regForm = new vista.FrmRegistro();
        regForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem_REGISTRAR_USUARIOActionPerformed

    private void jMenuItem_REGISTRAR_CLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_REGISTRAR_CLIENTEActionPerformed
        // TODO add your handling code here:
        vista.FrmRegistroClientes regFormCli = new vista.FrmRegistroClientes();
        regFormCli.setVisible(true);
    }//GEN-LAST:event_jMenuItem_REGISTRAR_CLIENTEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_REGISTRAR_CLIENTE;
    public javax.swing.JMenuItem jMenuItem_REGISTRAR_USUARIO;
    private javax.swing.JMenu jMenu_AGENDA;
    private javax.swing.JMenu jMenu_CLIENTES;
    private javax.swing.JMenu jMenu_INICIO;
    private javax.swing.JMenu jMenu_MASCOTAS;
    private javax.swing.JMenu jMenu_PRODUCTOS;
    private javax.swing.JMenu jMenu_PROVEEDORES;
    public javax.swing.JMenu jMenu_USUARIOS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
