/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.RoundedBorder;
import java.awt.Color;
import javax.swing.JFrame;
import modelo.Conexion_DB;
import java.sql.Connection;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Cathecita
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
        jButton_ATENDERmascota.setFocusPainted(false);
        Color verdeOliva = Color.decode("#588157");
        RoundedBorder bordeRedondeado = new RoundedBorder(15, verdeOliva);
        jButton_ATENDERmascota.setBorder(bordeRedondeado);

       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_VENDER = new javax.swing.JButton();
        jButton_SALIR = new javax.swing.JButton();
        jButton_ATENDERmascota = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_USUARIOS = new javax.swing.JMenu();
        jMenuItem_ADMINISTRAR_USUARIOS = new javax.swing.JMenuItem();
        jMenuItem_REGISTRAR_USUARIO = new javax.swing.JMenuItem();
        jMenu_CLIENTES = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem_REGISTRAR_CLIENTE = new javax.swing.JMenuItem();
        jMenu_PROVEEDORES = new javax.swing.JMenu();
        jMenu_PRODUCTOS = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 215, 205));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/webpetdef 50px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 78, 65));
        jLabel3.setText("Bienvenid@ a WebPet, el mejor software de gestión veterinaria.");

        jButton_VENDER.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton_VENDER.setForeground(new java.awt.Color(52, 78, 65));
        jButton_VENDER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-vender-webpet-app.png"))); // NOI18N
        jButton_VENDER.setText("VENDER");
        jButton_VENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VENDERActionPerformed(evt);
            }
        });

        jButton_SALIR.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton_SALIR.setForeground(new java.awt.Color(52, 78, 65));
        jButton_SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-salir-webpet-app.png"))); // NOI18N
        jButton_SALIR.setText("SALIR");
        jButton_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SALIRActionPerformed(evt);
            }
        });

        jButton_ATENDERmascota.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton_ATENDERmascota.setForeground(new java.awt.Color(52, 78, 65));
        jButton_ATENDERmascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-atender-servicio-webpet-app.png"))); // NOI18N
        jButton_ATENDERmascota.setText("ATENDER");
        jButton_ATENDERmascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ATENDERmascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButton_ATENDERmascota, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_VENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_VENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ATENDERmascota, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(163, 177, 138));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Hecho con ♥ por Catherine Escobar SENA ADSO CBA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu_USUARIOS.setBackground(new java.awt.Color(255, 255, 255));
        jMenu_USUARIOS.setText("USUARIOS DEL SISTEMA  |");
        jMenu_USUARIOS.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenu_USUARIOS.setMinimumSize(new java.awt.Dimension(105, 30));
        jMenu_USUARIOS.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem_ADMINISTRAR_USUARIOS.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem_ADMINISTRAR_USUARIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/buscar-icono-webpet.png"))); // NOI18N
        jMenuItem_ADMINISTRAR_USUARIOS.setText("Administrar");
        jMenuItem_ADMINISTRAR_USUARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ADMINISTRAR_USUARIOSActionPerformed(evt);
            }
        });
        jMenu_USUARIOS.add(jMenuItem_ADMINISTRAR_USUARIOS);

        jMenuItem_REGISTRAR_USUARIO.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem_REGISTRAR_USUARIO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-agregar-webpet-app.png"))); // NOI18N
        jMenuItem_REGISTRAR_USUARIO.setText("Registrar");
        jMenuItem_REGISTRAR_USUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_REGISTRAR_USUARIOActionPerformed(evt);
            }
        });
        jMenu_USUARIOS.add(jMenuItem_REGISTRAR_USUARIO);

        jMenuBar1.add(jMenu_USUARIOS);

        jMenu_CLIENTES.setText("CLIENTES |");
        jMenu_CLIENTES.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenu_CLIENTES.setPreferredSize(new java.awt.Dimension(93, 50));

        jMenuItem1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/buscar-icono-webpet.png"))); // NOI18N
        jMenuItem1.setText("Administrar");
        jMenu_CLIENTES.add(jMenuItem1);

        jMenuItem_REGISTRAR_CLIENTE.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuItem_REGISTRAR_CLIENTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-agregar-webpet-app.png"))); // NOI18N
        jMenuItem_REGISTRAR_CLIENTE.setText("Registrar");
        jMenuItem_REGISTRAR_CLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_REGISTRAR_CLIENTEActionPerformed(evt);
            }
        });
        jMenu_CLIENTES.add(jMenuItem_REGISTRAR_CLIENTE);

        jMenuBar1.add(jMenu_CLIENTES);

        jMenu_PROVEEDORES.setText("PROVEEDORES |");
        jMenu_PROVEEDORES.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenu_PROVEEDORES.setPreferredSize(new java.awt.Dimension(137, 50));
        jMenuBar1.add(jMenu_PROVEEDORES);

        jMenu_PRODUCTOS.setText("PRODUCTOS");
        jMenu_PRODUCTOS.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jMenu_PRODUCTOS.setPreferredSize(new java.awt.Dimension(109, 50));
        jMenuBar1.add(jMenu_PRODUCTOS);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        setSize(new java.awt.Dimension(916, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_REGISTRAR_USUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_REGISTRAR_USUARIOActionPerformed
        // TODO add your handling code here:
        vista.FrmUsuariosRegistrar regForm = new vista.FrmUsuariosRegistrar();
        regForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem_REGISTRAR_USUARIOActionPerformed

    private void jMenuItem_REGISTRAR_CLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_REGISTRAR_CLIENTEActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuItem_REGISTRAR_CLIENTEActionPerformed

    private void jMenuItem_ADMINISTRAR_USUARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ADMINISTRAR_USUARIOSActionPerformed
        // TODO add your handling code here:
        vista.FrmUsuariosAdministrar usuariosForm = new vista.FrmUsuariosAdministrar();
        usuariosForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ADMINISTRAR_USUARIOSActionPerformed

    private void jButton_VENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VENDERActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton_VENDERActionPerformed

    private void jButton_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SALIRActionPerformed
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de que desea salir del sistema?",
        "Confirmar salida",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            Connection con = Conexion_DB.getConnection();
            if (con != null && !con.isClosed()) {
                con.close();
                System.out.println("Conexión cerrada correctamente");
            }
        } catch (Exception e) {
            System.out.println("Error al cerrar la conexión: " + e.getMessage());
        }

        this.dispose(); // Cierra FrmInicio

        // Abre de nuevo el login
        vista.FrmLogin login = new vista.FrmLogin(); // ajusta el paquete si es necesario
        login.setVisible(true);
    }
        
    }//GEN-LAST:event_jButton_SALIRActionPerformed

    private void jButton_ATENDERmascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ATENDERmascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ATENDERmascotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ATENDERmascota;
    private javax.swing.JButton jButton_SALIR;
    private javax.swing.JButton jButton_VENDER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem_ADMINISTRAR_USUARIOS;
    private javax.swing.JMenuItem jMenuItem_REGISTRAR_CLIENTE;
    public javax.swing.JMenuItem jMenuItem_REGISTRAR_USUARIO;
    private javax.swing.JMenu jMenu_CLIENTES;
    private javax.swing.JMenu jMenu_PRODUCTOS;
    private javax.swing.JMenu jMenu_PROVEEDORES;
    public javax.swing.JMenu jMenu_USUARIOS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
