/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Mascotas;
import java.awt.Color;
import java.math.BigInteger;
import java.security.MessageDigest;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Conexion_DB;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.util.List;

/**
 *
 * @author Cathecita
 */
public class FrmMascotasRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuariosRegistrar
     */
    //creamos objeto frmregistro para llamarlo desde login
    public static FrmLogin fl;
    private int cliente;
    private int idCliente;
    
    DefaultTableModel modeloMascotas;
    
    public FrmMascotasRegistrar() {
        initComponents();
        configurarTablaMascotas();
        
        //crear color
        //Color verdeOscuro = new Color(52,78,65);
        jTable_MASCOTASadd.setShowGrid(true);
        
        //Personalizar FRONT tabla colores según identidad corporativa webpet
        jTable_MASCOTASadd.setGridColor(Color.decode("#A3B18A"));
        jTable_MASCOTASadd.setSelectionBackground(Color.decode("#3A5A40"));
        jTable_MASCOTASadd.setSelectionForeground(Color.decode("#FFFFFF"));
        JTableHeader th = jTable_MASCOTASadd.getTableHeader();
        th.setFont(new Font("Montserrat", Font.BOLD, 12));
    }
    
    
    
    
    //Constructor con parámetro idcliente para cargar id cliente al registrar mascota
    public FrmMascotasRegistrar(int idCliente) {
        initComponents(); // Este método siempre debe estar
        this.idCliente = idCliente;
        System.out.println("ID del cliente recibido: " + idCliente);
        this.setLocationRelativeTo(null);
        configurarTablaMascotas();
}
    
    private void configurarTablaMascotas() {
        modeloMascotas = new DefaultTableModel(
            new Object[]{"Nombre", "Especie", "Género", "Raza", "Color", "Edad"}, 0
        );
    jTable_MASCOTASadd.setModel(modeloMascotas);

    // Personalización
    jTable_MASCOTASadd.setShowGrid(true);
    jTable_MASCOTASadd.setGridColor(Color.decode("#A3B18A"));
    jTable_MASCOTASadd.setSelectionBackground(Color.decode("#3A5A40"));
    jTable_MASCOTASadd.setSelectionForeground(Color.decode("#FFFFFF"));
    JTableHeader th = jTable_MASCOTASadd.getTableHeader();
    th.setFont(new Font("Montserrat", Font.BOLD, 12));
}
    
    //TRAER la lista desde jtable
    public List<Mascotas> obtenerMascotasDeTabla(int idCliente) {
        List<Mascotas> listaMascotas = new ArrayList<>();

        for (int i = 0; i < jTable_MASCOTASadd.getRowCount(); i++) {
            String nombre = jTable_MASCOTASadd.getValueAt(i, 0).toString();
            String especie = jTable_MASCOTASadd.getValueAt(i, 1).toString();
            String genero = jTable_MASCOTASadd.getValueAt(i, 2).toString();
            String raza = jTable_MASCOTASadd.getValueAt(i, 3).toString();
            String color = jTable_MASCOTASadd.getValueAt(i, 4).toString();
            String edad = jTable_MASCOTASadd.getValueAt(i, 5).toString();

            Mascotas mascota = new Mascotas(null, nombre, especie, genero, raza, color, edad, idCliente);
            listaMascotas.add(mascota);
        }

        return listaMascotas;
}
    
    public void limpiarTablaMascotas() {
    DefaultTableModel model = (DefaultTableModel) jTable_MASCOTASadd.getModel();
    model.setRowCount(0); // Limpia todas las filas
    }
    
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_nombreMASCOTA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_razaMASCOTA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_especieMASCOTA = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField_edadMASCOTAS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_colorMASCOTA = new javax.swing.JTextField();
        jButton_agregarMASCOTAtabla = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_generoMASCOTA = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Inicio = new javax.swing.JButton();
        jButton_SALIRmascotas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_MASCOTASadd = new javax.swing.JTable();
        jButton_GuardarMASCOTAS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 78, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/webpetdef 50px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(218, 215, 205));
        jLabel3.setText("Somos tu mejor aliado en la gestión veterinaria, WebPet");

        jPanel2.setBackground(new java.awt.Color(218, 215, 205));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(88, 129, 87)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nombre");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Raza");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Especie");

        jComboBox_especieMASCOTA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "CANINA", "FELINA", "EQUINA", "AVES", "BOVINOS", "PORCINA", " ", " ", " " }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Edad");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Color");

        jButton_agregarMASCOTAtabla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_agregarMASCOTAtabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-derecha-webpet-app.png"))); // NOI18N
        jButton_agregarMASCOTAtabla.setText("Enviar a lista");
        jButton_agregarMASCOTAtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_agregarMASCOTAtablaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_agregarMASCOTAtablaMouseExited(evt);
            }
        });
        jButton_agregarMASCOTAtabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarMASCOTAtablaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Género");

        jComboBox_generoMASCOTA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "HEMBRA", "MACHO", " ", " ", " " }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_generoMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_agregarMASCOTAtabla, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nombreMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_razaMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_especieMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_colorMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_edadMASCOTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_nombreMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_especieMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox_generoMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_razaMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_colorMASCOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_edadMASCOTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jButton_agregarMASCOTAtabla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(218, 215, 205));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Hecho con ♥ por Catherine Escobar SENA ADSO CBA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(218, 215, 205));
        jLabel18.setText("REGISTRO DE MASCOTAS");

        Inicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-home-webpet-app.png"))); // NOI18N
        Inicio.setText("Inicio");

        jButton_SALIRmascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-salir-webpet-app.png"))); // NOI18N
        jButton_SALIRmascotas.setText("Salir");
        jButton_SALIRmascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SALIRmascotasActionPerformed(evt);
            }
        });

        jTable_MASCOTASadd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_MASCOTASadd);

        jButton_GuardarMASCOTAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-agregar-webpet-app.png"))); // NOI18N
        jButton_GuardarMASCOTAS.setText("Guardar Mascotas");
        jButton_GuardarMASCOTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarMASCOTASActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_SALIRmascotas)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton_GuardarMASCOTAS)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SALIRmascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_GuardarMASCOTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(475, 475, 475))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(916, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_agregarMASCOTAtablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarMASCOTAtablaActionPerformed
        // TODO add your handling code here:
        String nombre = jTextField_nombreMASCOTA.getText();
        String especie = jComboBox_especieMASCOTA.getSelectedItem().toString();
        String genero = jComboBox_generoMASCOTA.getSelectedItem().toString();
        String raza = jTextField_razaMASCOTA.getText();
        String color = jTextField_colorMASCOTA.getText();
        String edad = jTextField_edadMASCOTAS.getText();
        //verificar campos llenos
        if (nombre.isEmpty() || especie.trim().equals("Seleccione") ||genero.trim().equals("Seleccione") || raza.isEmpty() || color.isEmpty() || edad.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Completa todos los campos.");
        return;
        }
        //agregar fila a jtable
        modeloMascotas.addRow(new Object[]{nombre, especie, genero, raza, color, edad});
        
        //limpiar campos después de agregar a jtable
        jTextField_nombreMASCOTA.setText("");
        jComboBox_especieMASCOTA.setSelectedItem("Seleccione");
        jComboBox_generoMASCOTA.setSelectedItem("Seleccione");
        jTextField_razaMASCOTA.setText("");
        jTextField_colorMASCOTA.setText("");
        jTextField_edadMASCOTAS.setText("");
        
        
    }//GEN-LAST:event_jButton_agregarMASCOTAtablaActionPerformed

    private void jButton_agregarMASCOTAtablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_agregarMASCOTAtablaMouseEntered
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton_agregarMASCOTAtablaMouseEntered

    private void jButton_agregarMASCOTAtablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_agregarMASCOTAtablaMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_agregarMASCOTAtablaMouseExited

    private void jButton_GuardarMASCOTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarMASCOTASActionPerformed
        // TODO add your handling code here:
        try {
            int idCliente = this.idCliente; // O la variable donde guardas el id del cliente
            List<Mascotas> listaMascotas = obtenerMascotasDeTabla(idCliente);

        if (listaMascotas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay mascotas para guardar");
            return;
        }

        Mascotas.insertarVariasMascotas(listaMascotas);

        // Opcional: limpiar tabla después de guardar
        limpiarTablaMascotas();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar mascotas: " + e.getMessage());
        }
        
                    

    }//GEN-LAST:event_jButton_GuardarMASCOTASActionPerformed

    private void jButton_SALIRmascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SALIRmascotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SALIRmascotasActionPerformed

    
    
    public boolean verificarCampos()
    {
        String nombre = jTextField_nombreMASCOTA.getText();
        String especie= jComboBox_especieMASCOTA.getSelectedItem().toString();
        String raza = jTextField_razaMASCOTA.getText();
        String color = jTextField_colorMASCOTA.getText();
        String edad = jTextField_edadMASCOTAS.getText();
        
        // verificar campos llenos
        if(nombre.trim().equals("") || especie.trim().equals("Seleccione") || raza.trim().equals("")
           || color.trim().equals("") || edad.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Uno o más campos están vacíos o sin selección","Campos vacíos",2);
            return false;
        }
        
        // if everything is ok
        else{
            return true;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMascotasRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMascotasRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMascotasRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMascotasRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMascotasRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inicio;
    private javax.swing.JButton jButton_GuardarMASCOTAS;
    private javax.swing.JButton jButton_SALIRmascotas;
    private javax.swing.JButton jButton_agregarMASCOTAtabla;
    private javax.swing.JComboBox<String> jComboBox_especieMASCOTA;
    private javax.swing.JComboBox<String> jComboBox_generoMASCOTA;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_MASCOTASadd;
    private javax.swing.JTextField jTextField_colorMASCOTA;
    private javax.swing.JTextField jTextField_edadMASCOTAS;
    private javax.swing.JTextField jTextField_nombreMASCOTA;
    private javax.swing.JTextField jTextField_razaMASCOTA;
    // End of variables declaration//GEN-END:variables
}
