/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import modelo.Conexion_DB;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import vista.FrmClientesActualizar;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;



/**
 *
 * @author Cathecita
 */
public class FrmProductosAdministrar extends javax.swing.JFrame {

    private List<Integer> listaIdProveedores = new ArrayList<>();

    
    public FrmProductosAdministrar() {
        initComponents();
        llenarTablaProductos();  
        //crear color
        //Color verdeOscuro = new Color(52,78,65);
        jTable_PRODUCTOS.setShowGrid(true);
        
        //Personalizar FRONT tabla colores según identidad corporativa webpet
        jTable_PRODUCTOS.setGridColor(Color.decode("#A3B18A"));
        jTable_PRODUCTOS.setSelectionBackground(Color.decode("#3A5A40"));
        jTable_PRODUCTOS.setSelectionForeground(Color.decode("#FFFFFF"));
        JTableHeader th = jTable_PRODUCTOS.getTableHeader();
        th.setFont(new Font("Montserrat", Font.BOLD, 12));
        
        
        
    }
    
    private void llenarTablaProductos() {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Categoría");
    modelo.addColumn("Código");
    modelo.addColumn("Nombre");
    modelo.addColumn("Cantidad");
    modelo.addColumn("PVP");

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    try {
        con = Conexion_DB.getConnection();
        String sql = "SELECT c.categoria, p.codigo_producto, p.nombre_producto, p.cantidad_producto, p.precio_venta " +
                     "FROM productos p " +
                     "INNER JOIN categorias c ON p.fk_id_categoria = c.id_categoria";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();

        while (rs.next()) {
            Object[] fila = new Object[5];
            fila[0] = rs.getString("categoria");
            fila[1] = rs.getString("codigo_producto");
            fila[2] = rs.getString("nombre_producto");
            fila[3] = rs.getInt("cantidad_producto");
            fila[4] = rs.getBigDecimal("precio_venta");
            modelo.addRow(fila);
        }

        jTable_PRODUCTOS.setModel(modelo);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al llenar la tabla de productos: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (con != null) con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage());
        }
    }
}

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_BUSCAR_PRODUCTOS = new javax.swing.JButton();
        jButton_ACTUALIZAR_PRODUCTOS = new javax.swing.JButton();
        jTextField_VALOR_BUSQUEDA_PRODUCTOS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_PRODUCTOS = new javax.swing.JTable();
        jButton_registrarPRODUCTOS = new javax.swing.JButton();
        jButton_editarPRODUCTOSeleccionado = new javax.swing.JButton();
        jButton_volverInicio = new javax.swing.JButton();
        jButton_eliminarPRODUCTOSeleccionado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 78, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/logo webpet beige.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(218, 215, 205));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Hecho con ♥ por Catherine Escobar SENA ADSO CBA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jButton_BUSCAR_PRODUCTOS.setBackground(new java.awt.Color(218, 215, 205));
        jButton_BUSCAR_PRODUCTOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_BUSCAR_PRODUCTOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/buscar-icono-webpet.png"))); // NOI18N
        jButton_BUSCAR_PRODUCTOS.setText("Buscar");
        jButton_BUSCAR_PRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BUSCAR_PRODUCTOSActionPerformed(evt);
            }
        });

        jButton_ACTUALIZAR_PRODUCTOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ACTUALIZAR_PRODUCTOS.setForeground(new java.awt.Color(52, 78, 65));
        jButton_ACTUALIZAR_PRODUCTOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-actualizar-webpet-app.png"))); // NOI18N
        jButton_ACTUALIZAR_PRODUCTOS.setText("Actualizar");
        jButton_ACTUALIZAR_PRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ACTUALIZAR_PRODUCTOSActionPerformed(evt);
            }
        });

        jTextField_VALOR_BUSQUEDA_PRODUCTOS.setBackground(new java.awt.Color(218, 215, 205));
        jTextField_VALOR_BUSQUEDA_PRODUCTOS.setForeground(new java.awt.Color(52, 78, 65));
        jTextField_VALOR_BUSQUEDA_PRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_VALOR_BUSQUEDA_PRODUCTOSActionPerformed(evt);
            }
        });

        jTable_PRODUCTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_PRODUCTOS);

        jButton_registrarPRODUCTOS.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jButton_registrarPRODUCTOS.setForeground(new java.awt.Color(52, 78, 65));
        jButton_registrarPRODUCTOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-agregar-webpet-app.png"))); // NOI18N
        jButton_registrarPRODUCTOS.setText("Registrar Producto");
        jButton_registrarPRODUCTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarPRODUCTOSActionPerformed(evt);
            }
        });

        jButton_editarPRODUCTOSeleccionado.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jButton_editarPRODUCTOSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-editar-webpet-app.png"))); // NOI18N
        jButton_editarPRODUCTOSeleccionado.setText("Editar Producto  Seleccionado");
        jButton_editarPRODUCTOSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarPRODUCTOSeleccionadoActionPerformed(evt);
            }
        });

        jButton_volverInicio.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jButton_volverInicio.setForeground(new java.awt.Color(52, 78, 65));
        jButton_volverInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-home-webpet-app.png"))); // NOI18N
        jButton_volverInicio.setText("Inicio");
        jButton_volverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverInicioActionPerformed(evt);
            }
        });

        jButton_eliminarPRODUCTOSeleccionado.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jButton_eliminarPRODUCTOSeleccionado.setForeground(new java.awt.Color(52, 78, 65));
        jButton_eliminarPRODUCTOSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-eliminar-webpet-app.png"))); // NOI18N
        jButton_eliminarPRODUCTOSeleccionado.setText("Eliminar Producto Seleccionado");
        jButton_eliminarPRODUCTOSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarPRODUCTOSeleccionadoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(218, 215, 205));
        jLabel3.setText("ADMINISTRAR PRODUCTOS Y CATEGORIAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_editarPRODUCTOSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_registrarPRODUCTOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_volverInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_eliminarPRODUCTOSeleccionado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_VALOR_BUSQUEDA_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_BUSCAR_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ACTUALIZAR_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(jButton_editarPRODUCTOSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_eliminarPRODUCTOSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_registrarPRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_volverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_ACTUALIZAR_PRODUCTOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_BUSCAR_PRODUCTOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_VALOR_BUSQUEDA_PRODUCTOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(916, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BUSCAR_PRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BUSCAR_PRODUCTOSActionPerformed
        // TODO add your handling code here:
        String valorBusqueda = jTextField_VALOR_BUSQUEDA_PRODUCTOS.getText().trim();

DefaultTableModel modelo = new DefaultTableModel();
modelo.addColumn("Categoría");
modelo.addColumn("Código");
modelo.addColumn("Nombre");
modelo.addColumn("Cantidad");
modelo.addColumn("PVP");

Connection con = null;
PreparedStatement pst = null;
ResultSet rs = null;

try {
    con = Conexion_DB.getConnection();
    String sql = "SELECT c.categoria, p.codigo_producto, p.nombre_producto, p.cantidad_producto, p.precio_venta " +
                 "FROM productos p " +
                 "INNER JOIN categorias c ON p.id_categoria = c.id_categoria " +
                 "WHERE p.nombre_producto LIKE ? OR p.codigo_producto LIKE ?";

    pst = con.prepareStatement(sql);
    pst.setString(1, "%" + valorBusqueda + "%");
    pst.setString(2, "%" + valorBusqueda + "%");

    rs = pst.executeQuery();

    while (rs.next()) {
        Object[] fila = new Object[5];
        fila[0] = rs.getString("categoria");
        fila[1] = rs.getString("codigo_producto");
        fila[2] = rs.getString("nombre_producto");
        fila[3] = rs.getInt("cantidad_producto");
        fila[4] = rs.getBigDecimal("precio_venta");
        modelo.addRow(fila);
    }

    jTable_PRODUCTOS.setModel(modelo);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error al buscar productos: " + e.getMessage());
} finally {
    try {
        if (rs != null) rs.close();
        if (pst != null) pst.close();
        if (con != null) con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cerrar la conexión: " + e.getMessage());
    }
}

          
    
    }//GEN-LAST:event_jButton_BUSCAR_PRODUCTOSActionPerformed

    private void jButton_registrarPRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarPRODUCTOSActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton_registrarPRODUCTOSActionPerformed

    private void jButton_editarPRODUCTOSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarPRODUCTOSeleccionadoActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_jButton_editarPRODUCTOSeleccionadoActionPerformed

    private void jButton_volverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverInicioActionPerformed
        // TODO add your handling code here:
        vista.FrmInicio inicioForm = new vista.FrmInicio();
        inicioForm.setVisible(true);
        this.dispose(); 
        
    }//GEN-LAST:event_jButton_volverInicioActionPerformed

    private void jButton_eliminarPRODUCTOSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarPRODUCTOSeleccionadoActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jButton_eliminarPRODUCTOSeleccionadoActionPerformed

    private void jButton_ACTUALIZAR_PRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ACTUALIZAR_PRODUCTOSActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_ACTUALIZAR_PRODUCTOSActionPerformed

    private void jTextField_VALOR_BUSQUEDA_PRODUCTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_VALOR_BUSQUEDA_PRODUCTOSActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_VALOR_BUSQUEDA_PRODUCTOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductosAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductosAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductosAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductosAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductosAdministrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ACTUALIZAR_PRODUCTOS;
    private javax.swing.JButton jButton_BUSCAR_PRODUCTOS;
    private javax.swing.JButton jButton_editarPRODUCTOSeleccionado;
    private javax.swing.JButton jButton_eliminarPRODUCTOSeleccionado;
    private javax.swing.JButton jButton_registrarPRODUCTOS;
    private javax.swing.JButton jButton_volverInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_PRODUCTOS;
    private javax.swing.JTextField jTextField_VALOR_BUSQUEDA_PRODUCTOS;
    // End of variables declaration//GEN-END:variables
}
