/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;


/**
 *
 * @author Cathecita
 */
public class FrmUsuariosAdministrar extends javax.swing.JFrame {

    controlador.Usuarios user;
    
    public FrmUsuariosAdministrar() {
        initComponents();
        
        //llenar la tabla para usar el query de búsqueda
        llenarJtableParam("");
        
        //crear color
        //Color verdeOscuro = new Color(52,78,65);
        jTable_USUARIOS.setShowGrid(true);
        
        //Personalizar FRONT tabla colores según identidad corporativa webpet
        jTable_USUARIOS.setGridColor(Color.decode("#A3B18A"));
        jTable_USUARIOS.setSelectionBackground(Color.decode("#3A5A40"));
        jTable_USUARIOS.setSelectionForeground(Color.decode("#FFFFFF"));
        JTableHeader th = jTable_USUARIOS.getTableHeader();
        th.setFont(new Font("Montserrat", Font.BOLD, 12));
        
        
        
    }
    
    public void llenarJtableParam(String val){
        
        controlador.Usuarios usu = new controlador.Usuarios();
        ArrayList<controlador.Usuarios> listaUsuario = usu.usuariosList(val);
        
        String[] colNames = {"ID","Nombre","Apellido","Documento","Email","Usuario","Rol"};
        Object[][] rows = new Object[listaUsuario.size()][7];
        
        for(int i = 0; i < listaUsuario.size(); i++){
            rows[i][0] = listaUsuario.get(i).getId();
            rows[i][1] = listaUsuario.get(i).getPri_nom_usuario();
            rows[i][2] = listaUsuario.get(i).getPri_apell_usuario();
            rows[i][3] = listaUsuario.get(i).getNum_doc_usuario();
            rows[i][4] = listaUsuario.get(i).getEmail_usuario();
            rows[i][5] = listaUsuario.get(i).getUsuario();
            rows[i][6] = listaUsuario.get(i).getRol_usuario();
            

        }
        
        modelo.MyTableModelUsuarios mmd = new modelo.MyTableModelUsuarios(rows, colNames);
        jTable_USUARIOS.setModel(mmd);
        jTable_USUARIOS.setRowHeight(30);
        jTable_USUARIOS.getColumnModel().getColumn(6).setPreferredWidth(120);
        
        //Ocultar la columna ID pero sigue disponible para luego llamar la info para actualizar
        
        jTable_USUARIOS.getColumnModel().getColumn(0).setMinWidth(0);
        jTable_USUARIOS.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable_USUARIOS.getColumnModel().getColumn(0).setWidth(0);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_BUSCAR_USUARIOS = new javax.swing.JButton();
        jButton_ACTUALIZAR_USUARIOS = new javax.swing.JButton();
        jTextField_VALOR_BUSQUEDA_USUARIOS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_USUARIOS = new javax.swing.JTable();
        jButton_registrarUsuario = new javax.swing.JButton();
        jButton_editarUsuarioSeleccionado = new javax.swing.JButton();
        jButton_volverInicio = new javax.swing.JButton();
        jButton_eliminarUsuarioSeleccionado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 78, 65));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/webpetdef 50px.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(218, 215, 205));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Hecho con ♥ por Catherine Escobar SENA ADSO CBA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jButton_BUSCAR_USUARIOS.setBackground(new java.awt.Color(218, 215, 205));
        jButton_BUSCAR_USUARIOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_BUSCAR_USUARIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/buscar-icono-webpet.png"))); // NOI18N
        jButton_BUSCAR_USUARIOS.setText("Buscar");
        jButton_BUSCAR_USUARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BUSCAR_USUARIOSActionPerformed(evt);
            }
        });

        jButton_ACTUALIZAR_USUARIOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ACTUALIZAR_USUARIOS.setForeground(new java.awt.Color(52, 78, 65));
        jButton_ACTUALIZAR_USUARIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-actualizar-webpet-app.png"))); // NOI18N
        jButton_ACTUALIZAR_USUARIOS.setText("Actualizar");

        jTextField_VALOR_BUSQUEDA_USUARIOS.setBackground(new java.awt.Color(218, 215, 205));
        jTextField_VALOR_BUSQUEDA_USUARIOS.setForeground(new java.awt.Color(52, 78, 65));

        jTable_USUARIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_USUARIOS);

        jButton_registrarUsuario.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jButton_registrarUsuario.setForeground(new java.awt.Color(52, 78, 65));
        jButton_registrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-agregar-webpet-app.png"))); // NOI18N
        jButton_registrarUsuario.setText("Registrar Usuario");
        jButton_registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarUsuarioActionPerformed(evt);
            }
        });

        jButton_editarUsuarioSeleccionado.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jButton_editarUsuarioSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-editar-webpet-app.png"))); // NOI18N
        jButton_editarUsuarioSeleccionado.setText("Editar Usuario Seleccionado");
        jButton_editarUsuarioSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editarUsuarioSeleccionadoActionPerformed(evt);
            }
        });

        jButton_volverInicio.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jButton_volverInicio.setForeground(new java.awt.Color(52, 78, 65));
        jButton_volverInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-home-webpet-app.png"))); // NOI18N
        jButton_volverInicio.setText("Volver a INICIO");
        jButton_volverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverInicioActionPerformed(evt);
            }
        });

        jButton_eliminarUsuarioSeleccionado.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jButton_eliminarUsuarioSeleccionado.setForeground(new java.awt.Color(52, 78, 65));
        jButton_eliminarUsuarioSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/icono-eliminar-webpet-app.png"))); // NOI18N
        jButton_eliminarUsuarioSeleccionado.setText("Eliminar Usuario Seleccionado");
        jButton_eliminarUsuarioSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarUsuarioSeleccionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_editarUsuarioSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_registrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_volverInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_eliminarUsuarioSeleccionado))
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_VALOR_BUSQUEDA_USUARIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_BUSCAR_USUARIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ACTUALIZAR_USUARIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(61, 61, 61)
                        .addComponent(jButton_editarUsuarioSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_eliminarUsuarioSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_registrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_volverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButton_ACTUALIZAR_USUARIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_BUSCAR_USUARIOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_VALOR_BUSQUEDA_USUARIOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(916, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BUSCAR_USUARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BUSCAR_USUARIOSActionPerformed
        // TODO add your handling code here:
         llenarJtableParam(jTextField_VALOR_BUSQUEDA_USUARIOS.getText());
    }//GEN-LAST:event_jButton_BUSCAR_USUARIOSActionPerformed

    private void jButton_registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarUsuarioActionPerformed
        // TODO add your handling code here:
        FrmUsuariosRegistrar registrarUsuarioForm = new FrmUsuariosRegistrar();
            registrarUsuarioForm.pack();
            registrarUsuarioForm.setVisible(true);
            registrarUsuarioForm.setLocationRelativeTo(null);
            registrarUsuarioForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_registrarUsuarioActionPerformed

    private void jButton_editarUsuarioSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editarUsuarioSeleccionadoActionPerformed
        // TODO add your handling code here:
        try {
        int filaSeleccionada = jTable_USUARIOS.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un usuario de la tabla", "Sin usuarios seleccionados", 2);
            return;
        }
        // Obtener el ID oculto
        int idUsuario = Integer.parseInt(jTable_USUARIOS.getValueAt(filaSeleccionada, 0).toString());

        // Buscar el usuario completo desde la base de datos (esto es importante)
        controlador.Usuarios usuarioCompleto = controlador.Usuarios.buscarUsuarioPorId(idUsuario);

        FrmUsuariosActualizar actualizarUsuariosForm = new FrmUsuariosActualizar();
        actualizarUsuariosForm.usuarioId = usuarioCompleto.getId();
        actualizarUsuariosForm.jTextField_pnombre.setText(usuarioCompleto.getPri_nom_usuario());
        actualizarUsuariosForm.jTextField_snombre.setText(usuarioCompleto.getSeg_nom_usuario());
        actualizarUsuariosForm.jTextField_papellido.setText(usuarioCompleto.getPri_apell_usuario());
        actualizarUsuariosForm.jTextField_sapellido.setText(usuarioCompleto.getSeg_apell_usuario());
        actualizarUsuariosForm.jComboBox_tipodoc.setSelectedItem(usuarioCompleto.getTipo_doc_usuario());
        actualizarUsuariosForm.jTextField_numdoc.setText(usuarioCompleto.getNum_doc_usuario());
        actualizarUsuariosForm.jTextField_email.setText(usuarioCompleto.getEmail_usuario());
        actualizarUsuariosForm.jTextField_tel.setText(usuarioCompleto.getTel_usuario());
        actualizarUsuariosForm.jTextField_dir.setText(usuarioCompleto.getDir_usuario());
        actualizarUsuariosForm.jTextField_usuario.setText(usuarioCompleto.getUsuario());
        actualizarUsuariosForm.jPasswordField_pass.setText(usuarioCompleto.getPasswd_usuario());
        actualizarUsuariosForm.jComboBox_rol.setSelectedItem(usuarioCompleto.getRol_usuario());

        actualizarUsuariosForm.setVisible(true);
        actualizarUsuariosForm.pack();
        actualizarUsuariosForm.setLocationRelativeTo(null);
        actualizarUsuariosForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error al abrir formulario de edición: " + e.getMessage());
    }
        
        /*
        try{

            // open the edit product form and display data into the fields
            FrmUsuariosActualizar actualizarUsuariosForm = new FrmUsuariosActualizar();
            int filaSeleccionada = jTable_USUARIOS.getSelectedRow();
            
            Integer rowIndex = jTable_USUARIOS.getSelectedRow();
            
            

            actualizarUsuariosForm.usuarioId = Integer.valueOf(jTable_USUARIOS.getValueAt(rowIndex, 0).toString());
            actualizarUsuariosForm.jTextField_pnombre.setText(jTable_USUARIOS.getValueAt(rowIndex, 1).toString());
            actualizarUsuariosForm.jTextField_snombre.setText(jTable_USUARIOS.getValueAt(rowIndex, 2).toString());
            actualizarUsuariosForm.jTextField_papellido.setText(jTable_USUARIOS.getValueAt(rowIndex, 3).toString());
            actualizarUsuariosForm.jTextField_sapellido.setText(jTable_USUARIOS.getValueAt(rowIndex, 4).toString());
            actualizarUsuariosForm.jComboBox_tipodoc.setSelectedItem(jTable_USUARIOS.getValueAt(rowIndex, 5));
            actualizarUsuariosForm.jTextField_numdoc.setText(jTable_USUARIOS.getValueAt(rowIndex, 6).toString());
            actualizarUsuariosForm.jTextField_email.setText(jTable_USUARIOS.getValueAt(rowIndex, 7).toString());
            actualizarUsuariosForm.jTextField_tel.setText(jTable_USUARIOS.getValueAt(rowIndex, 8).toString());
            actualizarUsuariosForm.jTextField_dir.setText(jTable_USUARIOS.getValueAt(rowIndex, 9).toString());
            actualizarUsuariosForm.jTextField_usuario.setText(jTable_USUARIOS.getValueAt(rowIndex, 10).toString());
            actualizarUsuariosForm.jPasswordField_pass.setText(jTable_USUARIOS.getValueAt(rowIndex, 11).toString());
            actualizarUsuariosForm.jComboBox_rol.setSelectedItem(jTable_USUARIOS.getValueAt(rowIndex, 12));
          
            actualizarUsuariosForm.setVisible(true);
                    actualizarUsuariosForm.pack();
                    actualizarUsuariosForm.setLocationRelativeTo(null);
                    actualizarUsuariosForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }catch(Exception Ex){
            JOptionPane.showMessageDialog(null, "Seleccione un usuario de la tabla", "Sin usuarios seleccionados", 2);
        }*/
    }//GEN-LAST:event_jButton_editarUsuarioSeleccionadoActionPerformed

    private void jButton_volverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverInicioActionPerformed
        // TODO add your handling code here:
        vista.FrmInicio inicioForm = new vista.FrmInicio();
        inicioForm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton_volverInicioActionPerformed

    private void jButton_eliminarUsuarioSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarUsuarioSeleccionadoActionPerformed
        // TODO add your handling code here:
        int fila = jTable_USUARIOS.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Por favor seleccione un usuario de la tabla.");
                return;
            }

        // Confirmación antes de eliminar
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas eliminar este usuario?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            
            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }

            try {
        // Traer la lista completa para acceder al ID 
            controlador.Usuarios usu = new controlador.Usuarios();
            ArrayList<controlador.Usuarios> listaUsuarios = usu.usuariosList(""); 

        // El ID está en la posición de la lista, no en la tabla, porque la tabla solo muestra 6 campos
            int idUsuario = listaUsuarios.get(fila).getId();

        // Llamar método para eliminar
            controlador.Usuarios.eliminarUsuarioPorId(idUsuario);

        // Refrescar tabla
            llenarJtableParam("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al intentar eliminar el usuario: " + e.getMessage());
                e.printStackTrace();
            }

        
    }//GEN-LAST:event_jButton_eliminarUsuarioSeleccionadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuariosAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuariosAdministrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ACTUALIZAR_USUARIOS;
    private javax.swing.JButton jButton_BUSCAR_USUARIOS;
    private javax.swing.JButton jButton_editarUsuarioSeleccionado;
    private javax.swing.JButton jButton_eliminarUsuarioSeleccionado;
    private javax.swing.JButton jButton_registrarUsuario;
    private javax.swing.JButton jButton_volverInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_USUARIOS;
    private javax.swing.JTextField jTextField_VALOR_BUSQUEDA_USUARIOS;
    // End of variables declaration//GEN-END:variables
}
